#define FileSystem = Environment.LoadInterface("FileSystem", {})
#define Http = Environment.LoadInterface("Http", {})
#custom INCLUDE_IO(!file)
{
	if(FileSystem.Exists(file))
	{
		return FileSystem.ReadAll(file)
	}
	else
	{
		Error("Can not Include File: " + file)
		return ""
	}
}
#custom INCLUDE_WEB(!url)
{
	response = Http.Get(url)
	if(response.Status == 100)
	{
		return response.Body
	}
	else
	{
		Error("Can not Get File '" + url + "' Error Code: " + response.Status)
		return ""
	}
}