namespace InteractiveShell.Console.Commands
{
	using InteractiveShell.Console
	class ListCommand : InteractiveShellConsoleCommand
	{
		function ListCommand() : base("list") { }

		function RunCommand(!args)
		{
			Console.WriteLine("Available Commands:")
			foreach cmd in Instance._commands
			{
				Console.WriteLine($"\t- {cmd.ToString()}")
			}
		}

		function ToString()
		{
			return "'list' : Print All Console Commands."
		}
	}
}