namespace InteractiveShell.Console.Commands
{
	using InteractiveShell.Console
	class WriteReturnCommand : InteractiveShellConsoleCommand
	{
		function WriteReturnCommand() : base("write-return") { }

		function RunCommand(!args)
		{
			Instance._writeReturn = !Instance._writeReturn
			
			Console.WriteLine("Write Return: " + Instance._writeReturn)
		}

		function ToString()
		{
			return "'write-return' : Toggle Write Return Flag."
		}
	}
}