//Install(or Load) Module System
environment.loadString(environment.loadInterface("http", {}).downloadString("http://static.byt3.dev/apps/BadScript/modules-core/modules_install.bs")).load()

//Load Interface for IO
fs = environment.loadInterface("fs", {})

function runProgram()
{
	//Require the interactive shell module
	shell = modules.require("interactive-shell")
	logging = modules.require("logging")

	log = logging.create("MAIN")

	log("Running Shell..")
	//Use Interactive Shell Module
	shell.runShell()

	log("Uninstalling Module System..")
	//Uninstall Module System to keep Git Repository Clean
	fs.delete("modules.bs")
	fs.delete("modules", 1)
}

runProgram()
