fs = environment.loadInterface("fs", {})
http = environment.loadInterface("http", {})
moduleCoreInstallUrl = "http://static.byt3.dev/apps/BadScript/modules-core/install.bs"


function install()
{
	response = http.get(moduleCoreInstallUrl)
	if(response.status != 200)
	{
		error("Module Core Installer was not found. Status: " + response.status)
	}
	else
	{
		installSource = response.body
		installer = environment.loadString(installSource)
		installer.run()
	}
}


function load()
{
	if(fs.exists("./modules.bs") == 0)
	{
		install()
	}
}