codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "60...90"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

# ignore Non-Required BS interfaces
ignore:
  - "src/BadScript.Http"  
  - "src/BadScript.Http.Server"  
  - "src/BadScript.Imaging"  
  - "src/BadScript.IO"  
  - "src/BadScript.Json"  
  - "src/BadScript.Math"  
  - "src/BadScript.Process"  
  - "src/BadScript.StringUtils"  
  - "src/BadScript.Testing"  
  - "src/BadScript.Tools.CodeGenerator"  
  - "src/BadScript.Tools.CodeGenerator.Runtime"  
  - "src/BadScript.Utils"  
  - "src/BadScript.Xml"  
  - "src/BadScript.Zip"  