//Load Server
server = modules.require("http-server")

//Load Json Serialization Helper
json = environment.loadInterface("json", {})

//Define Function to get called for a specific endpoint
function hello_world(ctx)
{
	//Get Response Object
	response = ctx.response()

	//Construct Body
	body = {}
	body.message = "Hello World"

	//Write Body to the Response Stream
	response.writeBody(json.toJson(body))

	//Send off the Response
	response.close()
}

//Add Endpoint
server.add("/v1/hello_world", hello_world)

//List of URIs to listen on
prefixes = ["http://localhost:1234/v1/"]

//Start the Server
server.start(prefixes)
