fs = environment.loadInterface("fs", {})
path = environment.loadInterface("path", {})


ppDir = path.combine(args[0], "preprocessors")
if(fs.exists(ppDir) == 0)
{
	fs.createDir(ppDir)
}

ppfiles = fs.getFiles(ppDir, "*.bs", 1)
pps = []
foreach ppfile in ppfiles
{
	pps.add(environment.loadString(fs.readAll(ppfile)))
}

foreach pp in pps
{
	print("[PP-LOADER] Loading Preprocessor: " + pp.name)
	environment.addPreprocessor(pp.name, pp)
}