http = environment.loadInterface("http", {})
path = environment.loadInterface("path", {})

if(args == null)
{
	error("No Arguments. Expected Syntax: wget <url> [<destination>]")
}
if(args.size() == 0 ||
	args.size() > 2)
{
	error("No Arguments. Expected Syntax: wget <url> [<destination>]")
}

srcUrl = args[0]
dstUrl = null
if(args.size() == 2)
{
	dstUrl = args[1]
}
else
{
	dstUrl = path.getFullPath(path.getFileName(srcUrl))
}

print("[GET] " + srcUrl)
http.downloadFile(srcUrl, dstUrl)
