//Load Required Interfaces
environment.loadInterface("fs")

//Loader Table Root
loader = {}

//Returns the Local Path to the source file relative to the root of the repository
loader.getLocalDir = function(!repoDir, !name) => return path.combine(repoDir, name, name + ".bs") 

//Returns true if the repository contains the requested module name
loader.has = function(!repoDir, !name)
{
	p = loader.getLocalDir(repoDir, name)
	if(fs.exists(p))
	{
		return fs.isFile(p)
	}
	return 0
}

//Returns the source of the specified module
loader.get = function(!repoDir, !name)
{
	localPath = loader.getLocalDir(repoDir, name)
	src = fs.readAll(localPath)
	return src
}

return loader