namespace System.Tests
{
	using System

	passNoArgs = false
	passArgs = false
	function subscriber0()
	{
		passNoArgs = true
	}

	function subscriber1(arg)
	{
		passArgs = true
	}

	ev0 = new Event()
	ev0 += subscriber0
	ev0()

	ev1 = new Event(1)
	ev1 += subscriber1
	ev1("Argument Test")

	pass = true
	if(!passNoArgs)
	{
		print("[TEST] Event with no Args Failed!")
		pass = false
	}
	if(!passArgs)
	{
		print("[TEST] Event with Args Failed!")
		pass = false
	}

	if(!pass)
	{
		error("Event Tests Failed")
	}
}