if(args == null)
{
	error("Server is not passed to HTTP Server Extension")
	return null
}
if(args.size() == 0)
{
	error("Server is not passed to HTTP Server Extension")
	return null
}

server = args[0]

json = environment.loadInterface("json")

//Hello World Endpoint

function hello_world(ctx)
{
	response = ctx.response()
	response.writeBody(json.toJson({message = "Hello World"}))
	response.close()
}

server.add("/hello_world", hello_world)
