
A = {}

for i = 0 while< 10 step 1
{
	A["for i = 0 while< 10 step 1 ++++ " + i] = i
}
for i = 0 while<= 10 step 1
{
	A["for i = 0 while<= 10 step 1 ++++ " + i] = i
}

function f(x)
{
	return x < 10
}

B = []

for i = 0 while f(i)
{
	B[i] = i
}



foreach x in B
{
	A["foreach x in B ++++ " + x] = x
}



resultCount = 31

kCount = 0
foreach key in A
{
	kCount = kCount + 1
}

kvCount = 0
foreach (key, value) in A
{
	kvCount = kvCount + 1
}

if(kCount != resultCount)
{
	print("\t[FAILED]For Each(Key)")
}
else if(kvCount != resultCount)
{
	print("\t[FAILED]For Each(Key,Value)!")
}
else if(resultCount != size(A))
{
	print("\t[FAILED]For Test!")
}
else
{
	print("\t[PASSED]For Tests!")
}