
function BadShellMain()
{
	args = ProcessInfo.GetArguments()
	args.RemoveAt(0)
	onlyFiles = false
	if(args.Size() != 0)
	{
		if(args[0] == "--file")
		{
			onlyFiles = true
			args.RemoveAt(0)
		}
	}
	exit = false
	shell = new BadShellModule(ProcessInfo, Extensions, args, function() => exit = true)
	if(!onlyFiles)
	{
		while(!exit)
		{
			shell.OnUpdate()
			Environment.Sleep(250)
		}
	}

}

BadShellMain()