loader = {}

function getModuleIndexUrl(!repoDir) => return path.combine(repoDir, "index.json")
function getTempModuleDirectory()
{
	p = path.combine(modules.getDataPath(), "temp", "static-web")
	fs.createDir(p)
	return p
}

function loadModuleIndex(!repoDir)
{
	indexUrl = getModuleIndexUrl(repoDir)
	response = http.get(indexUrl)
	if(response.status == 200)
	{
		return json2bs(response.body)
	}
	modules.logger.error(string.format("Could not reach Repository(response code: {0})", response.status))
}

loader.has = function(!repoDir, !name)
{
	index = loadModuleIndex(repoDir)
	foreach module in index
	{
		if(module == name)
		{
			return 1
		}
	}
	return 0
}

loader.get = function(!repoDir, !name)
{
	remotePath = path.combine(repoDir, name, name + ".bs")
	src = http.downloadString(remotePath)
	return src
}

return loader