
A = {}

for i = 0 while< 10 step 1
{
	A["for i = 0 while< 10 step 1 ++++ " + i] = i
	print(i)
}
for i = 0 while<= 10 step 1
{
	A["for i = 0 while<= 10 step 1 ++++ " + i] = i
	print(i)
}

function f(x)
{
	return x < 10
}

B = []

for i = 0 while f(i)
{
	B[i] = i
	print(i)
}



foreach x in B
{
	A["foreach x in B ++++ " + x] = x
	print("FOREACH " + x)
}

foreach key in A
{
	print(key + " = " + A[key])
}


foreach (key, value) in A
{
	print(key + " = " + value)
}