if(fs == null && json2bs == null && bs2json == null)
{
	print("Missing Dependencies to load plugin JSON")
	return {}
}

function load(path)
{
	if(fs.exists(path) && fs.isFile(path))
	{
		f = fs.open(path)
		src = f.readAll()
		f.close()
		return json2bs(src)
	}
	else
	{
		print("Invalid File: " + path)
	}
}

function save(path, obj)
{
	if(fs.exists(path))
	{
		fs.delete(path)
	}

	f = fs.open(path)
	src = bs2json(obj)
	print(src)
	f.write(src)
	f.close()
	print("Saved File: " + path)
}