fs = environment.loadInterface("fs", {})
path = environment.loadInterface("path", {})

function findRepo(!repoName)
	{
		foreach repo in modules.repositories
		{
			if(repo.name == repoName)
			{
				return repo
			}
		}
		error("Could not find Repository with name: " + repoName)
	}

global function module_sync_local(!repoName, !name)
{
	print("Syncing Module: " + name)

	localDir = findRepo(repoName).url

	dir = modules.loaders.local.getLocalDir(localDir, name)

	fs.createDir(path.getDirectoryName(dir))

	src = modules.requireSource(name)

	fs.writeAll(dir, src)

}

global function module_clear_cache()
{
	print("Clearing Module Cache...")
	modules.moduleCache = {}
}
